# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Captain Cue' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
#use_modular_headers!
  # Pods for Captain Cue
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Core'
  pod 'FirebaseStorage'
  pod 'ObjectMapper'
	pod 'RealmSwift'
	pod 'Material'
	pod 'M13Checkbox'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'M13ProgressSuite'
  pod 'ReachabilitySwift'
  
  target 'Captain CueTests' do
    inherit! :complete#search_paths
    # Pods for testing
  end

  target 'Captain CueUITests' do
    # Pods for testing
  end

end
