# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Captain Cue' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Captain Cue

	pod 'RealmSwift'
	pod 'Material'
	pod 'M13Checkbox'

  target 'Captain CueTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Captain CueUITests' do
    # Pods for testing
  end

end
